name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        run: |
          curl --request POST \
          --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
          --header 'accept: application/json' \
          --header 'authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '
          {
            "clearCache": "do_not_clear"
          }
          ' -v